config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  scope "(:locale)", locale: /en|sw/ do
   root to: "home#index"
   devise_for :users, controllers: {
           :registrations => "users/registrations",
           :sessions => "users/sessions",
           confirmations: 'users/confirmations' }
    get "/login", :to => "devise/sessions#new"
    resources :customers
    get 'contact_books', to: 'contact_books#generate_number'
    patch 'contact_books', to: 'contact_books#update_number'
    post 'verify', to: 'customers#verify'
    get 'customers', to: 'customers#index'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

   attr_accessor :address ,:city
   belongs_to :service_provider
   belongs_to :user
   has_many :contact_books, as: :contactable
   has_many :addresses, as: :addressable

   has_one_attached :aadhar_image
   validates :aadhar_number, presence: true, numericality: { only_integer: true }, length: { is: 12 }
   validates :email, presence: true, uniqueness: true
   validates :first_name, :last_name, presence: true, length: { minimum: 2 }
   # validates :aadhar_image, presence: true 
   attr_accessor :phone

   after_update :sim_activated

   after_create :customer_mailer

   def customer_mailer
     CustomerMailer.new_customer_create(self).deliver_now
   end

   def sim_activated
      if contact_books.activated
        CustomerMailer.update_status(self).deliver_now
      else 
        puts "not"
      end
   end
end

app/controllers/customers_controller.rb
pclass CustomersController < ApplicationController

   include Utility

  def new
    @customer = Customer.new
    @customer.phone = generate_number
  end

  def verify
    @phone_no = ContactBook.find_by(phone: params[:phone])
    
    flash_message = @phone_no.present? ? { notice: "Phone number is already present in the database." } : { alert: "Phone number is not present in the database." }
    
    redirect_to new_customer_path, flash: flash_message
  end

  def create
    @service_provider = current_user.service_provider
    @customer = @service_provider.customers.build(customer_params.merge(user_id: current_user.id))

    if @customer.save
      @address = @customer.addresses.new(address_params)
      @address.save

      @contact = @customer.contact_books.new(phone: params[:phone])
      @contact.save
      
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @customer = Customer.all 
    @customer_details = @customer.includes([:addresses],[:contact_books])
     render :index
  end


  def show 
     @customer = Customer.find(params[:id])
  end


   private
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :aadhar_number, :aadhar_image)
    end

    def address_params
       params.require(:customer).permit(:address, :city)
    end

    # def contact_params
    #    params.require(:customer).permit(:phone)
    # end
end

app/views/customers/index.html.erb
<h1>Customer Details</h1>

<table border>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>City</th>
      <th>Contact Books</th>
    </tr>
  </thead>
  <tbody>
    <%  @customer_details.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
         <td>
          <% customer.addresses.each do |address| %>
            <%= address.address %>
          <% end %>
        </td>
        <td>
          <% customer.addresses.each do |city| %>
            <%= city.city %>
          <% end %>
        </td>
        <td>
          <% customer.contact_books.each do |contact_book| %>
            <%= contact_book.phone %>
          <% end %>
        </td>      
      </tr>
    <% end %>

  </tbody>

</table>

app/views/customers/new.html.erb
<h1><%= t "customer" %></h1>

<% if flash[:notice] %>
  <h2>Customer Created Successfully</h2>
<% end %>

<%= form_with model: @customer do |form| %>
  <div>
    <%= form.label :first_name, "#{t('first_name')}" %><br>
    <%= form.text_field :first_name %>
    <% @customer.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :last_name, "#{t('last_name')}" %><br>
    <%= form.text_field :last_name %><br>
    <% @customer.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email, "#{t('email')}" %><br>
    <%= form.text_field :email %>
    <% @customer.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :aadhar_number, "#{t('aadhar_num')}" %><br>
    <%= form.text_field :aadhar_number %>
    <% @customer.errors.full_messages_for(:aadhar_number).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :aadhar_image, "#{t('aadhar_img')}" %><br>
     <%= form.file_field :aadhar_image %>
    <% @customer.errors.full_messages_for(:aadhar_image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :address, "#{t('address')}" %><br>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :city , "#{t('city')}"%><br>
    <%= form.text_field :city %>
  </div>

 
  <%= form.label :phone, "#{t('phone')}" %><br>
  <div style="border: 1px solid black; padding: 10px; width: 100px;">
    <%=  form.hidden_field :phone, value:  @customer.phone %>
     <%= hidden_field_tag "phone", @customer.phone %>
   <%= @customer.phone %>
   <%= form.submit "Verify" ,formaction: verify_path, method: :post, data: { turbo: "true" } %>
  </div>

  <div>
    <%= form.submit "Create Customer"  %>
  </div>
<% end %>

app/views/customers/show.html.erb
<h1><%= @customer.first_name %></h1>
<h1><%= @customer.last_name %></h1>
<h1><%= @customer.email %></h1>
<h1><%= @customer.aadhar_number %></h1>
<h1><%= @customer.aadhar_image %></h1>

<h1>Addresses:</h1>
<% @customer.addresses.each do |add| %>
  <p>Address: <%= add.address %></p>
<% end %>

<h1>Phone Numbers:</h1>
<% @customer.contact_books.each do |contact| %> 
  <p>Phone: <%= contact.phone %></p>
<% end %>